//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using UnityEngine;
using System.Collections;

public class Note : MonoBehaviour
{
	public GameObject [] Notes;
	public bool nearNote = false;

	public Note ()
	{

	}
	void OnTriggerStay(Collider Collider)
	{
		//Debug.Log ("Possible note pickup");
		if(Collider.gameObject.tag == "Player")
		{
			Collider.gameObject.GetComponent<Notifications>().Notify("Press the interact key to pick up note.");
			//Debug.Log("Player near note");
			nearNote = true;
		}
	}

	void OnTriggerExit(Collider Collider)
	{
		if (Collider.gameObject.tag == "Player")
		{
			Collider.gameObject.GetComponent<Notifications>().ResetNotify();
			nearNote = false;
		}
	}

	
	void Update()
	{
		if (nearNote)
		{
			if (Input.GetButtonUp("Interact"))
			{
				Debug.Log("Interacted with note: " + gameObject.tag);
				if (gameObject.CompareTag("Note0")){
					ActivateNote(0);
				}else if (gameObject.CompareTag("Note1")){
					ActivateNote(1);
				}
                gameObject.SetActive(false);
			}
		}
	}

	public void ActivateNote(int i)
	{
		Debug.Log ("Activating note #" + i);
		//showNote (i);
		if (i == 0) {
			GameObject.Find ("Player").GetComponent<Notifications> ().Notify ("Get some gas");
            GameObject.Find("null").GetComponent<Manager>().ActivateNote(0);
		} else if (i == 1) {
			GameObject.Find ("Player").GetComponent<Notifications> ().Notify ("Get a flashlight");
            GameObject.Find("null").GetComponent<Manager>().ActivateNote(1);
        }
		StartCoroutine("Wait");
	}

	public void showNote(int i){
		GameObject.Find ("NotesCanvas").SetActive (true);
		GameObject.Find ("NoteImage").SetActive (true);

		
		GameObject.Find ("NoteImage").gameObject.GetComponent<MeshRenderer> ().material.mainTexture = (Texture3D)
			Resources.Load ("Note" + i, typeof(Texture3D)); 
	}


	IEnumerator Wait()
	{
		yield return new WaitForSeconds(2.5f);
        GameObject.FindGameObjectWithTag("Player").GetComponent<Notifications>().ResetNotify();
	}
	
}

