//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using UnityEngine;
using System.Collections;
	public class BackDoor : MonoBehaviour
	{
		
		void OnTriggerStay(Collider obj)
		{
			if(obj.tag == "Player")
			{
				GameObject.Find("null").GetComponent<Manager>().BackDoor();
			}
		}
		
		void OnTriggerExit(Collider Collider)
		{
			if (Collider.gameObject.tag == "Player")
			{
				Collider.gameObject.GetComponent<Notifications>().ResetNotify();
			}
		}



	}

